CREATE USER LabSystem IDENTIFIED BY "LabManage_67"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER,
CREATE PROCEDURE, CREATE TYPE TO LabSystem;