-- EQUIPMENT ASSIGNMENT
INSERT INTO equipment_assignment (serial_number, employee_id, assignment_date)
SELECT 'EQ001', 'SC001', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ002', 'SC002', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ003', 'SC003', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ004', 'SC004', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ005', 'SC005', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ025', 'SC006', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ026', 'SC007', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ027', 'SC008', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ028', 'SC009', TRUNC(SYSDATE) FROM dual
UNION ALL
SELECT 'EQ029', 'SC010', TRUNC(SYSDATE) FROM dual;