-- MATERIAL REQUESTS
INSERT INTO material_requests (
  reference_number,
  employee_id,
  request_date,
  material_quantity
)
SELECT 'MA001', 'SC001', TRUNC(SYSDATE), 5 FROM dual
UNION ALL
SELECT 'MA002', 'SC002', TRUNC(SYSDATE), 10 FROM dual
UNION ALL
SELECT 'MA025', 'SC003', TRUNC(SYSDATE), 7 FROM dual
UNION ALL
SELECT 'MA026', 'SC004', TRUNC(SYSDATE), 4 FROM dual
UNION ALL
SELECT 'MA027', 'SC005', TRUNC(SYSDATE), 6 FROM dual
UNION ALL
SELECT 'MA028', 'SC006', TRUNC(SYSDATE), 3 FROM dual
UNION ALL
SELECT 'MA029', 'SC007', TRUNC(SYSDATE), 8 FROM dual
UNION ALL
SELECT 'MA030', 'SC008', TRUNC(SYSDATE), 2 FROM dual
UNION ALL
SELECT 'MA031', 'SC009', TRUNC(SYSDATE), 9 FROM dual
UNION ALL
SELECT 'MA032', 'SC010', TRUNC(SYSDATE), 5 FROM dual;
